### ISSUE TITLE
Public API?

### ISSUE THREAD

**Issue by keikoro** [kanjialive/data-media#2]
Hi there, I noticed that the links to the API provided [on your info site](https://app.kanjialive.com/api/docs) are dead, and the API itself cannot be accessed without a key.

Would be interested in trying it out once it works again!

**Comment by kintopp** [comment]
The Mashape link has changed but the API is still active. You can request a key and [access it from here](https://market.mashape.com/kanjialive/learn-to-read-and-write-japanese-kanji/). Thanks for reminding us to update this in our docs.

**Comment by kintopp** [comment]
Finally updated https://app.kanjialive.com/api/docs with correct links to new RapidAPI hosted public api.

**Comment by keikoro** [comment]
Thank you!
