### ISSUE TITLE
Is there a pattern to the naming of Kanji Stroke Animation files?

### ISSUE THREAD

**Issue by Livinglist** [kanjialive/data-media#4]
For example, if I want to get the animation file of kanji "学", how should I do it?

**Comment by kintopp** [comment]
You'll find a file (ka_data.csv) with the necessary mappings in the [language-data](ka_data.csv) sub-directory. For 学 the kanji name (kname) is mana(bu). Depending on the suffix attached to this you'll be able to find the related kanji animations or stroke order images etc. In this case, mana(bu)_00.mp4. See the README texts in the different sub-directories. Alternatively, you can use the [public developer API](https://rapidapi.com/KanjiAlive/api/learn-to-read-and-write-japanese-kanji) documented [here](https://app.kanjialive.com/api/docs) to access the resources directly.
